//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", ConfigurationName="OgrenciService.OgrenciPort")]
    public interface OgrenciPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.StatuyeGoreOgrenciBirimIdIiResponse1> StatuyeGoreOgrenciBirimIdIiAsync(OgrenciService.StatuyeGoreOgrenciBirimIdIiRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.YokNoTCKimlikNoGuncelleResponse1> YokNoTCKimlikNoGuncelleAsync(OgrenciService.YokNoTCKimlikNoGuncelleRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.StatuyeGoreOgrenciSayisiResponse1> StatuyeGoreOgrenciSayisiAsync(OgrenciService.StatuyeGoreOgrenciSayisiRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.StatuBirimeGoreOgrenciResponse1> StatuBirimeGoreOgrenciAsync(OgrenciService.StatuBirimeGoreOgrenciRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.YuNoTCKimlikNoGuncelleResponse1> YuNoTCKimlikNoGuncelleAsync(OgrenciService.YuNoTCKimlikNoGuncelleRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.OgrenciEkleGuncelleResponse1> OgrenciEkleGuncelleAsync(OgrenciService.OgrenciEkleGuncelleRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.OgrenciSilResponse1> OgrenciSilAsync(OgrenciService.OgrenciSilRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.TeyitlesmeResponse1> TeyitlesmeAsync(OgrenciService.TeyitlesmeRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.YokNoYuNoGuncelleResponse1> YokNoYuNoGuncelleAsync(OgrenciService.YokNoYuNoGuncelleRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OgrenciService.YokYabanciOgrenciEkleResponse1> YokYabanciOgrenciEkleAsync(OgrenciService.YokYabanciOgrenciEkleRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class StatuyeGoreOgrenciBirimIdIiRequest
    {
        
        private OgrencilikStatusu ogrencilikStatusuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OgrencilikStatusu OgrencilikStatusu
        {
            get
            {
                return this.ogrencilikStatusuField;
            }
            set
            {
                this.ogrencilikStatusuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class OgrencilikStatusu
    {
        
        private int ogrencilikStatusu1Field;
        
        private int grupNoField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OgrencilikStatusu", Order=0)]
        public int OgrencilikStatusu1
        {
            get
            {
                return this.ogrencilikStatusu1Field;
            }
            set
            {
                this.ogrencilikStatusu1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int GrupNo
        {
            get
            {
                return this.grupNoField;
            }
            set
            {
                this.grupNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class Ogrenci
    {
        
        private long tcKimlikNoField;
        
        private long birimIdField;
        
        private int girisTuruField;
        
        private string girisPuaniField;
        
        private int girisPuanTuruField;
        
        private string ayrilmaNedeniField;
        
        private string ayrilmaTarihiField;
        
        private int sinifiField;
        
        private string kayitTarihiField;
        
        private int ogrencilikStatusuField;
        
        private string diplomaNoField;
        
        private int ogrencilikHakkiVarmiField;
        
        private string ogrencilikHakkiBittigiTarihField;
        
        private string engelTuruField;
        
        private string engelOraniField;
        
        private string aktifDonemNoField;
        
        private int gaziSehitYakiniField;
        
        private double diplomaNotuField;
        
        private bool diplomaNotuFieldSpecified;
        
        private double diplomaNotSistemiField;
        
        private double aktsField;
        
        private bool aktsFieldSpecified;
        
        private int hazirlikSinifiOkudumuField;
        
        private int kacDonemHazirlikSinifiOkuduField;
        
        private string ogrenciNoField;
        
        private string diplomaAdField;
        
        private string diplomaSoyadField;
        
        private System.Nullable<long> yatayBirimIdField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        private Apon ayniProgramOkumaNedeniField;
        
        private bool ayniProgramOkumaNedeniFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long BirimId
        {
            get
            {
                return this.birimIdField;
            }
            set
            {
                this.birimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GirisTuru
        {
            get
            {
                return this.girisTuruField;
            }
            set
            {
                this.girisTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GirisPuani
        {
            get
            {
                return this.girisPuaniField;
            }
            set
            {
                this.girisPuaniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int GirisPuanTuru
        {
            get
            {
                return this.girisPuanTuruField;
            }
            set
            {
                this.girisPuanTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=5)]
        public string AyrilmaNedeni
        {
            get
            {
                return this.ayrilmaNedeniField;
            }
            set
            {
                this.ayrilmaNedeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string AyrilmaTarihi
        {
            get
            {
                return this.ayrilmaTarihiField;
            }
            set
            {
                this.ayrilmaTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Sinifi
        {
            get
            {
                return this.sinifiField;
            }
            set
            {
                this.sinifiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string KayitTarihi
        {
            get
            {
                return this.kayitTarihiField;
            }
            set
            {
                this.kayitTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int OgrencilikStatusu
        {
            get
            {
                return this.ogrencilikStatusuField;
            }
            set
            {
                this.ogrencilikStatusuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string DiplomaNo
        {
            get
            {
                return this.diplomaNoField;
            }
            set
            {
                this.diplomaNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int OgrencilikHakkiVarmi
        {
            get
            {
                return this.ogrencilikHakkiVarmiField;
            }
            set
            {
                this.ogrencilikHakkiVarmiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string OgrencilikHakkiBittigiTarih
        {
            get
            {
                return this.ogrencilikHakkiBittigiTarihField;
            }
            set
            {
                this.ogrencilikHakkiBittigiTarihField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=13)]
        public string EngelTuru
        {
            get
            {
                return this.engelTuruField;
            }
            set
            {
                this.engelTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=14)]
        public string EngelOrani
        {
            get
            {
                return this.engelOraniField;
            }
            set
            {
                this.engelOraniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=15)]
        public string AktifDonemNo
        {
            get
            {
                return this.aktifDonemNoField;
            }
            set
            {
                this.aktifDonemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int GaziSehitYakini
        {
            get
            {
                return this.gaziSehitYakiniField;
            }
            set
            {
                this.gaziSehitYakiniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double DiplomaNotu
        {
            get
            {
                return this.diplomaNotuField;
            }
            set
            {
                this.diplomaNotuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiplomaNotuSpecified
        {
            get
            {
                return this.diplomaNotuFieldSpecified;
            }
            set
            {
                this.diplomaNotuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double DiplomaNotSistemi
        {
            get
            {
                return this.diplomaNotSistemiField;
            }
            set
            {
                this.diplomaNotSistemiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double Akts
        {
            get
            {
                return this.aktsField;
            }
            set
            {
                this.aktsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktsSpecified
        {
            get
            {
                return this.aktsFieldSpecified;
            }
            set
            {
                this.aktsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int HazirlikSinifiOkudumu
        {
            get
            {
                return this.hazirlikSinifiOkudumuField;
            }
            set
            {
                this.hazirlikSinifiOkudumuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int KacDonemHazirlikSinifiOkudu
        {
            get
            {
                return this.kacDonemHazirlikSinifiOkuduField;
            }
            set
            {
                this.kacDonemHazirlikSinifiOkuduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string OgrenciNo
        {
            get
            {
                return this.ogrenciNoField;
            }
            set
            {
                this.ogrenciNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string DiplomaAd
        {
            get
            {
                return this.diplomaAdField;
            }
            set
            {
                this.diplomaAdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string DiplomaSoyad
        {
            get
            {
                return this.diplomaSoyadField;
            }
            set
            {
                this.diplomaSoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<long> YatayBirimId
        {
            get
            {
                return this.yatayBirimIdField;
            }
            set
            {
                this.yatayBirimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public Apon AyniProgramOkumaNedeni
        {
            get
            {
                return this.ayniProgramOkumaNedeniField;
            }
            set
            {
                this.ayniProgramOkumaNedeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AyniProgramOkumaNedeniSpecified
        {
            get
            {
                return this.ayniProgramOkumaNedeniFieldSpecified;
            }
            set
            {
                this.ayniProgramOkumaNedeniFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public enum Apon
    {
        
        /// <remarks/>
        NORMAL_KAYIT,
        
        /// <remarks/>
        AYNI_PROGRAMA_TEKRAR_KAYIT,
        
        /// <remarks/>
        AYNI_PROGRAMA_AF_ILE_KAYIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class Sonuc
    {
        
        private int kodField;
        
        private string aciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class StatuyeGoreOgrenciBirimIdIiResponse
    {
        
        private OgrencilerBirimId[] ogrencilerBirimIdField;
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OgrencilerBirimId", Order=0)]
        public OgrencilerBirimId[] OgrencilerBirimId
        {
            get
            {
                return this.ogrencilerBirimIdField;
            }
            set
            {
                this.ogrencilerBirimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class OgrencilerBirimId
    {
        
        private long tcKimlikNoField;
        
        private bool tcKimlikNoFieldSpecified;
        
        private long birimIdField;
        
        private bool birimIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TcKimlikNoSpecified
        {
            get
            {
                return this.tcKimlikNoFieldSpecified;
            }
            set
            {
                this.tcKimlikNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long BirimId
        {
            get
            {
                return this.birimIdField;
            }
            set
            {
                this.birimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirimIdSpecified
        {
            get
            {
                return this.birimIdFieldSpecified;
            }
            set
            {
                this.birimIdFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatuyeGoreOgrenciBirimIdIiRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.StatuyeGoreOgrenciBirimIdIiRequest StatuyeGoreOgrenciBirimIdIiRequest;
        
        public StatuyeGoreOgrenciBirimIdIiRequest1()
        {
        }
        
        public StatuyeGoreOgrenciBirimIdIiRequest1(OgrenciService.StatuyeGoreOgrenciBirimIdIiRequest StatuyeGoreOgrenciBirimIdIiRequest)
        {
            this.StatuyeGoreOgrenciBirimIdIiRequest = StatuyeGoreOgrenciBirimIdIiRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatuyeGoreOgrenciBirimIdIiResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.StatuyeGoreOgrenciBirimIdIiResponse StatuyeGoreOgrenciBirimIdIiResponse;
        
        public StatuyeGoreOgrenciBirimIdIiResponse1()
        {
        }
        
        public StatuyeGoreOgrenciBirimIdIiResponse1(OgrenciService.StatuyeGoreOgrenciBirimIdIiResponse StatuyeGoreOgrenciBirimIdIiResponse)
        {
            this.StatuyeGoreOgrenciBirimIdIiResponse = StatuyeGoreOgrenciBirimIdIiResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokNoTCKimlikNoGuncelleRequest
    {
        
        private YokNoTCKimlikNo yokNoTCKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public YokNoTCKimlikNo YokNoTCKimlikNo
        {
            get
            {
                return this.yokNoTCKimlikNoField;
            }
            set
            {
                this.yokNoTCKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokNoTCKimlikNo
    {
        
        private long yokNoField;
        
        private long tcKimlikNoField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long YokNo
        {
            get
            {
                return this.yokNoField;
            }
            set
            {
                this.yokNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokNoTCKimlikNoGuncelleResponse
    {
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YokNoTCKimlikNoGuncelleRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.YokNoTCKimlikNoGuncelleRequest YokNoTCKimlikNoGuncelleRequest;
        
        public YokNoTCKimlikNoGuncelleRequest1()
        {
        }
        
        public YokNoTCKimlikNoGuncelleRequest1(OgrenciService.YokNoTCKimlikNoGuncelleRequest YokNoTCKimlikNoGuncelleRequest)
        {
            this.YokNoTCKimlikNoGuncelleRequest = YokNoTCKimlikNoGuncelleRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YokNoTCKimlikNoGuncelleResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.YokNoTCKimlikNoGuncelleResponse YokNoTCKimlikNoGuncelleResponse;
        
        public YokNoTCKimlikNoGuncelleResponse1()
        {
        }
        
        public YokNoTCKimlikNoGuncelleResponse1(OgrenciService.YokNoTCKimlikNoGuncelleResponse YokNoTCKimlikNoGuncelleResponse)
        {
            this.YokNoTCKimlikNoGuncelleResponse = YokNoTCKimlikNoGuncelleResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class StatuyeGoreOgrenciSayisiRequest
    {
        
        private StatuyeGoreOgrenciSayisi statuyeGoreOgrenciSayisiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatuyeGoreOgrenciSayisi StatuyeGoreOgrenciSayisi
        {
            get
            {
                return this.statuyeGoreOgrenciSayisiField;
            }
            set
            {
                this.statuyeGoreOgrenciSayisiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class StatuyeGoreOgrenciSayisi
    {
        
        private int ogrencilikStatusuField;
        
        private long grupSayisiField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OgrencilikStatusu
        {
            get
            {
                return this.ogrencilikStatusuField;
            }
            set
            {
                this.ogrencilikStatusuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long GrupSayisi
        {
            get
            {
                return this.grupSayisiField;
            }
            set
            {
                this.grupSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class StatuyeGoreOgrenciSayisiResponse
    {
        
        private StatuyeGoreOgrenciSayisi statuyeGoreOgrenciSayisiField;
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatuyeGoreOgrenciSayisi StatuyeGoreOgrenciSayisi
        {
            get
            {
                return this.statuyeGoreOgrenciSayisiField;
            }
            set
            {
                this.statuyeGoreOgrenciSayisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatuyeGoreOgrenciSayisiRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.StatuyeGoreOgrenciSayisiRequest StatuyeGoreOgrenciSayisiRequest;
        
        public StatuyeGoreOgrenciSayisiRequest1()
        {
        }
        
        public StatuyeGoreOgrenciSayisiRequest1(OgrenciService.StatuyeGoreOgrenciSayisiRequest StatuyeGoreOgrenciSayisiRequest)
        {
            this.StatuyeGoreOgrenciSayisiRequest = StatuyeGoreOgrenciSayisiRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatuyeGoreOgrenciSayisiResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.StatuyeGoreOgrenciSayisiResponse StatuyeGoreOgrenciSayisiResponse;
        
        public StatuyeGoreOgrenciSayisiResponse1()
        {
        }
        
        public StatuyeGoreOgrenciSayisiResponse1(OgrenciService.StatuyeGoreOgrenciSayisiResponse StatuyeGoreOgrenciSayisiResponse)
        {
            this.StatuyeGoreOgrenciSayisiResponse = StatuyeGoreOgrenciSayisiResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class StatuBirimeGoreOgrenciRequest
    {
        
        private OgrencilikStatusuBirim ogrencilikStatusuBirimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OgrencilikStatusuBirim OgrencilikStatusuBirim
        {
            get
            {
                return this.ogrencilikStatusuBirimField;
            }
            set
            {
                this.ogrencilikStatusuBirimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class OgrencilikStatusuBirim
    {
        
        private int ogrencilikStatusuField;
        
        private long birimIdField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OgrencilikStatusu
        {
            get
            {
                return this.ogrencilikStatusuField;
            }
            set
            {
                this.ogrencilikStatusuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long BirimId
        {
            get
            {
                return this.birimIdField;
            }
            set
            {
                this.birimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class StatuBirimeGoreOgrenciResponse
    {
        
        private OgrencilerBirimId[] ogrencilerBirimIdField;
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OgrencilerBirimId", Order=0)]
        public OgrencilerBirimId[] OgrencilerBirimId
        {
            get
            {
                return this.ogrencilerBirimIdField;
            }
            set
            {
                this.ogrencilerBirimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatuBirimeGoreOgrenciRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.StatuBirimeGoreOgrenciRequest StatuBirimeGoreOgrenciRequest;
        
        public StatuBirimeGoreOgrenciRequest1()
        {
        }
        
        public StatuBirimeGoreOgrenciRequest1(OgrenciService.StatuBirimeGoreOgrenciRequest StatuBirimeGoreOgrenciRequest)
        {
            this.StatuBirimeGoreOgrenciRequest = StatuBirimeGoreOgrenciRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatuBirimeGoreOgrenciResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.StatuBirimeGoreOgrenciResponse StatuBirimeGoreOgrenciResponse;
        
        public StatuBirimeGoreOgrenciResponse1()
        {
        }
        
        public StatuBirimeGoreOgrenciResponse1(OgrenciService.StatuBirimeGoreOgrenciResponse StatuBirimeGoreOgrenciResponse)
        {
            this.StatuBirimeGoreOgrenciResponse = StatuBirimeGoreOgrenciResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YuNoTCKimlikNoGuncelleRequest
    {
        
        private YuNoTCKimlikNo yuNoTCKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public YuNoTCKimlikNo YuNoTCKimlikNo
        {
            get
            {
                return this.yuNoTCKimlikNoField;
            }
            set
            {
                this.yuNoTCKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YuNoTCKimlikNo
    {
        
        private long yuNumarasiField;
        
        private long tcKimlikNoField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long YuNumarasi
        {
            get
            {
                return this.yuNumarasiField;
            }
            set
            {
                this.yuNumarasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YuNoTCKimlikNoGuncelleResponse
    {
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YuNoTCKimlikNoGuncelleRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.YuNoTCKimlikNoGuncelleRequest YuNoTCKimlikNoGuncelleRequest;
        
        public YuNoTCKimlikNoGuncelleRequest1()
        {
        }
        
        public YuNoTCKimlikNoGuncelleRequest1(OgrenciService.YuNoTCKimlikNoGuncelleRequest YuNoTCKimlikNoGuncelleRequest)
        {
            this.YuNoTCKimlikNoGuncelleRequest = YuNoTCKimlikNoGuncelleRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YuNoTCKimlikNoGuncelleResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.YuNoTCKimlikNoGuncelleResponse YuNoTCKimlikNoGuncelleResponse;
        
        public YuNoTCKimlikNoGuncelleResponse1()
        {
        }
        
        public YuNoTCKimlikNoGuncelleResponse1(OgrenciService.YuNoTCKimlikNoGuncelleResponse YuNoTCKimlikNoGuncelleResponse)
        {
            this.YuNoTCKimlikNoGuncelleResponse = YuNoTCKimlikNoGuncelleResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class OgrenciEkleGuncelleRequest
    {
        
        private Ogrenci ogrenciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Ogrenci Ogrenci
        {
            get
            {
                return this.ogrenciField;
            }
            set
            {
                this.ogrenciField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class OgrenciEkleGuncelleResponse
    {
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OgrenciEkleGuncelleRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.OgrenciEkleGuncelleRequest OgrenciEkleGuncelleRequest;
        
        public OgrenciEkleGuncelleRequest1()
        {
        }
        
        public OgrenciEkleGuncelleRequest1(OgrenciService.OgrenciEkleGuncelleRequest OgrenciEkleGuncelleRequest)
        {
            this.OgrenciEkleGuncelleRequest = OgrenciEkleGuncelleRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OgrenciEkleGuncelleResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.OgrenciEkleGuncelleResponse OgrenciEkleGuncelleResponse;
        
        public OgrenciEkleGuncelleResponse1()
        {
        }
        
        public OgrenciEkleGuncelleResponse1(OgrenciService.OgrenciEkleGuncelleResponse OgrenciEkleGuncelleResponse)
        {
            this.OgrenciEkleGuncelleResponse = OgrenciEkleGuncelleResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class OgrenciSilRequest
    {
        
        private OgrenciSil ogrenciSilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OgrenciSil OgrenciSil
        {
            get
            {
                return this.ogrenciSilField;
            }
            set
            {
                this.ogrenciSilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class OgrenciSil
    {
        
        private long tcKimlikNoField;
        
        private long birimIdField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long TcKimlikNo
        {
            get
            {
                return this.tcKimlikNoField;
            }
            set
            {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long BirimId
        {
            get
            {
                return this.birimIdField;
            }
            set
            {
                this.birimIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class OgrenciSilResponse
    {
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OgrenciSilRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.OgrenciSilRequest OgrenciSilRequest;
        
        public OgrenciSilRequest1()
        {
        }
        
        public OgrenciSilRequest1(OgrenciService.OgrenciSilRequest OgrenciSilRequest)
        {
            this.OgrenciSilRequest = OgrenciSilRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OgrenciSilResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.OgrenciSilResponse OgrenciSilResponse;
        
        public OgrenciSilResponse1()
        {
        }
        
        public OgrenciSilResponse1(OgrenciService.OgrenciSilResponse OgrenciSilResponse)
        {
            this.OgrenciSilResponse = OgrenciSilResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class TeyitlesmeRequest
    {
        
        private Teyit teyitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Teyit Teyit
        {
            get
            {
                return this.teyitField;
            }
            set
            {
                this.teyitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class Teyit
    {
        
        private string aktifField;
        
        private string izinliField;
        
        private string cezaliField;
        
        private string beklemeliField;
        
        private string pasifField;
        
        private string farabiGidenField;
        
        private string farabiGelenField;
        
        private string mevlanaGidenField;
        
        private string mevlanaGelenField;
        
        private string erasmusGidenField;
        
        private string erasmusGelenField;
        
        private string ozelGidenField;
        
        private string ozelGelenField;
        
        private string digerGidenField;
        
        private string digerGelenField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        private int kodField;
        
        private string aciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string Aktif
        {
            get
            {
                return this.aktifField;
            }
            set
            {
                this.aktifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string Izinli
        {
            get
            {
                return this.izinliField;
            }
            set
            {
                this.izinliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string Cezali
        {
            get
            {
                return this.cezaliField;
            }
            set
            {
                this.cezaliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string Beklemeli
        {
            get
            {
                return this.beklemeliField;
            }
            set
            {
                this.beklemeliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string Pasif
        {
            get
            {
                return this.pasifField;
            }
            set
            {
                this.pasifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string FarabiGiden
        {
            get
            {
                return this.farabiGidenField;
            }
            set
            {
                this.farabiGidenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string FarabiGelen
        {
            get
            {
                return this.farabiGelenField;
            }
            set
            {
                this.farabiGelenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string MevlanaGiden
        {
            get
            {
                return this.mevlanaGidenField;
            }
            set
            {
                this.mevlanaGidenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=8)]
        public string MevlanaGelen
        {
            get
            {
                return this.mevlanaGelenField;
            }
            set
            {
                this.mevlanaGelenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=9)]
        public string ErasmusGiden
        {
            get
            {
                return this.erasmusGidenField;
            }
            set
            {
                this.erasmusGidenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=10)]
        public string ErasmusGelen
        {
            get
            {
                return this.erasmusGelenField;
            }
            set
            {
                this.erasmusGelenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=11)]
        public string OzelGiden
        {
            get
            {
                return this.ozelGidenField;
            }
            set
            {
                this.ozelGidenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=12)]
        public string OzelGelen
        {
            get
            {
                return this.ozelGelenField;
            }
            set
            {
                this.ozelGelenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=13)]
        public string DigerGiden
        {
            get
            {
                return this.digerGidenField;
            }
            set
            {
                this.digerGidenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=14)]
        public string DigerGelen
        {
            get
            {
                return this.digerGelenField;
            }
            set
            {
                this.digerGelenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int Kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string Aciklama
        {
            get
            {
                return this.aciklamaField;
            }
            set
            {
                this.aciklamaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class TeyitlesmeResponse
    {
        
        private Teyit teyitField;
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Teyit Teyit
        {
            get
            {
                return this.teyitField;
            }
            set
            {
                this.teyitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TeyitlesmeRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.TeyitlesmeRequest TeyitlesmeRequest;
        
        public TeyitlesmeRequest1()
        {
        }
        
        public TeyitlesmeRequest1(OgrenciService.TeyitlesmeRequest TeyitlesmeRequest)
        {
            this.TeyitlesmeRequest = TeyitlesmeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TeyitlesmeResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.TeyitlesmeResponse TeyitlesmeResponse;
        
        public TeyitlesmeResponse1()
        {
        }
        
        public TeyitlesmeResponse1(OgrenciService.TeyitlesmeResponse TeyitlesmeResponse)
        {
            this.TeyitlesmeResponse = TeyitlesmeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokNoYuNoGuncelleRequest
    {
        
        private YokNoYuNo yokNoYuNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public YokNoYuNo YokNoYuNo
        {
            get
            {
                return this.yokNoYuNoField;
            }
            set
            {
                this.yokNoYuNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokNoYuNo
    {
        
        private long yokNoField;
        
        private long yuNumarasiField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long YokNo
        {
            get
            {
                return this.yokNoField;
            }
            set
            {
                this.yokNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long YuNumarasi
        {
            get
            {
                return this.yuNumarasiField;
            }
            set
            {
                this.yuNumarasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokNoYuNoGuncelleResponse
    {
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YokNoYuNoGuncelleRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.YokNoYuNoGuncelleRequest YokNoYuNoGuncelleRequest;
        
        public YokNoYuNoGuncelleRequest1()
        {
        }
        
        public YokNoYuNoGuncelleRequest1(OgrenciService.YokNoYuNoGuncelleRequest YokNoYuNoGuncelleRequest)
        {
            this.YokNoYuNoGuncelleRequest = YokNoYuNoGuncelleRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YokNoYuNoGuncelleResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.YokNoYuNoGuncelleResponse YokNoYuNoGuncelleResponse;
        
        public YokNoYuNoGuncelleResponse1()
        {
        }
        
        public YokNoYuNoGuncelleResponse1(OgrenciService.YokNoYuNoGuncelleResponse YokNoYuNoGuncelleResponse)
        {
            this.YokNoYuNoGuncelleResponse = YokNoYuNoGuncelleResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokYabanciOgrenciEkleRequest
    {
        
        private YokNoOgrenci yokNoOgrenciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public YokNoOgrenci YokNoOgrenci
        {
            get
            {
                return this.yokNoOgrenciField;
            }
            set
            {
                this.yokNoOgrenciField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokNoOgrenci
    {
        
        private long yokNoField;
        
        private string adField;
        
        private string soyadField;
        
        private string babaAdiField;
        
        private string anneAdiField;
        
        private int cinsiyetField;
        
        private string dogumTarihiField;
        
        private int uyrukField;
        
        private string pasaportNoField;
        
        private string kampKartNoField;
        
        private long yoksisUniversiteIdField;
        
        private string universiteSifreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long YokNo
        {
            get
            {
                return this.yokNoField;
            }
            set
            {
                this.yokNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ad
        {
            get
            {
                return this.adField;
            }
            set
            {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Soyad
        {
            get
            {
                return this.soyadField;
            }
            set
            {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BabaAdi
        {
            get
            {
                return this.babaAdiField;
            }
            set
            {
                this.babaAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AnneAdi
        {
            get
            {
                return this.anneAdiField;
            }
            set
            {
                this.anneAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Cinsiyet
        {
            get
            {
                return this.cinsiyetField;
            }
            set
            {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DogumTarihi
        {
            get
            {
                return this.dogumTarihiField;
            }
            set
            {
                this.dogumTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Uyruk
        {
            get
            {
                return this.uyrukField;
            }
            set
            {
                this.uyrukField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PasaportNo
        {
            get
            {
                return this.pasaportNoField;
            }
            set
            {
                this.pasaportNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string KampKartNo
        {
            get
            {
                return this.kampKartNoField;
            }
            set
            {
                this.kampKartNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long YoksisUniversiteId
        {
            get
            {
                return this.yoksisUniversiteIdField;
            }
            set
            {
                this.yoksisUniversiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UniversiteSifre
        {
            get
            {
                return this.universiteSifreField;
            }
            set
            {
                this.universiteSifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yok.gov.tr/ogrenci/2017/05")]
    public partial class YokYabanciOgrenciEkleResponse
    {
        
        private YokNoOgrenci yokNoOgrenciField;
        
        private Sonuc sonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public YokNoOgrenci YokNoOgrenci
        {
            get
            {
                return this.yokNoOgrenciField;
            }
            set
            {
                this.yokNoOgrenciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Sonuc Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YokYabanciOgrenciEkleRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.YokYabanciOgrenciEkleRequest YokYabanciOgrenciEkleRequest;
        
        public YokYabanciOgrenciEkleRequest1()
        {
        }
        
        public YokYabanciOgrenciEkleRequest1(OgrenciService.YokYabanciOgrenciEkleRequest YokYabanciOgrenciEkleRequest)
        {
            this.YokYabanciOgrenciEkleRequest = YokYabanciOgrenciEkleRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YokYabanciOgrenciEkleResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.yok.gov.tr/ogrenci/2017/05", Order=0)]
        public OgrenciService.YokYabanciOgrenciEkleResponse YokYabanciOgrenciEkleResponse;
        
        public YokYabanciOgrenciEkleResponse1()
        {
        }
        
        public YokYabanciOgrenciEkleResponse1(OgrenciService.YokYabanciOgrenciEkleResponse YokYabanciOgrenciEkleResponse)
        {
            this.YokYabanciOgrenciEkleResponse = YokYabanciOgrenciEkleResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface OgrenciPortChannel : OgrenciService.OgrenciPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OgrenciPortClient : System.ServiceModel.ClientBase<OgrenciService.OgrenciPort>, OgrenciService.OgrenciPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OgrenciPortClient() : 
                base(OgrenciPortClient.GetDefaultBinding(), OgrenciPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OgrenciPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OgrenciPortClient(EndpointConfiguration endpointConfiguration) : 
                base(OgrenciPortClient.GetBindingForEndpoint(endpointConfiguration), OgrenciPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OgrenciPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OgrenciPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OgrenciPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OgrenciPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OgrenciPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.StatuyeGoreOgrenciBirimIdIiResponse1> OgrenciService.OgrenciPort.StatuyeGoreOgrenciBirimIdIiAsync(OgrenciService.StatuyeGoreOgrenciBirimIdIiRequest1 request)
        {
            return base.Channel.StatuyeGoreOgrenciBirimIdIiAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.StatuyeGoreOgrenciBirimIdIiResponse1> StatuyeGoreOgrenciBirimIdIiAsync(OgrenciService.StatuyeGoreOgrenciBirimIdIiRequest StatuyeGoreOgrenciBirimIdIiRequest)
        {
            OgrenciService.StatuyeGoreOgrenciBirimIdIiRequest1 inValue = new OgrenciService.StatuyeGoreOgrenciBirimIdIiRequest1();
            inValue.StatuyeGoreOgrenciBirimIdIiRequest = StatuyeGoreOgrenciBirimIdIiRequest;
            return ((OgrenciService.OgrenciPort)(this)).StatuyeGoreOgrenciBirimIdIiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.YokNoTCKimlikNoGuncelleResponse1> OgrenciService.OgrenciPort.YokNoTCKimlikNoGuncelleAsync(OgrenciService.YokNoTCKimlikNoGuncelleRequest1 request)
        {
            return base.Channel.YokNoTCKimlikNoGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.YokNoTCKimlikNoGuncelleResponse1> YokNoTCKimlikNoGuncelleAsync(OgrenciService.YokNoTCKimlikNoGuncelleRequest YokNoTCKimlikNoGuncelleRequest)
        {
            OgrenciService.YokNoTCKimlikNoGuncelleRequest1 inValue = new OgrenciService.YokNoTCKimlikNoGuncelleRequest1();
            inValue.YokNoTCKimlikNoGuncelleRequest = YokNoTCKimlikNoGuncelleRequest;
            return ((OgrenciService.OgrenciPort)(this)).YokNoTCKimlikNoGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.StatuyeGoreOgrenciSayisiResponse1> OgrenciService.OgrenciPort.StatuyeGoreOgrenciSayisiAsync(OgrenciService.StatuyeGoreOgrenciSayisiRequest1 request)
        {
            return base.Channel.StatuyeGoreOgrenciSayisiAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.StatuyeGoreOgrenciSayisiResponse1> StatuyeGoreOgrenciSayisiAsync(OgrenciService.StatuyeGoreOgrenciSayisiRequest StatuyeGoreOgrenciSayisiRequest)
        {
            OgrenciService.StatuyeGoreOgrenciSayisiRequest1 inValue = new OgrenciService.StatuyeGoreOgrenciSayisiRequest1();
            inValue.StatuyeGoreOgrenciSayisiRequest = StatuyeGoreOgrenciSayisiRequest;
            return ((OgrenciService.OgrenciPort)(this)).StatuyeGoreOgrenciSayisiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.StatuBirimeGoreOgrenciResponse1> OgrenciService.OgrenciPort.StatuBirimeGoreOgrenciAsync(OgrenciService.StatuBirimeGoreOgrenciRequest1 request)
        {
            return base.Channel.StatuBirimeGoreOgrenciAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.StatuBirimeGoreOgrenciResponse1> StatuBirimeGoreOgrenciAsync(OgrenciService.StatuBirimeGoreOgrenciRequest StatuBirimeGoreOgrenciRequest)
        {
            OgrenciService.StatuBirimeGoreOgrenciRequest1 inValue = new OgrenciService.StatuBirimeGoreOgrenciRequest1();
            inValue.StatuBirimeGoreOgrenciRequest = StatuBirimeGoreOgrenciRequest;
            return ((OgrenciService.OgrenciPort)(this)).StatuBirimeGoreOgrenciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.YuNoTCKimlikNoGuncelleResponse1> OgrenciService.OgrenciPort.YuNoTCKimlikNoGuncelleAsync(OgrenciService.YuNoTCKimlikNoGuncelleRequest1 request)
        {
            return base.Channel.YuNoTCKimlikNoGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.YuNoTCKimlikNoGuncelleResponse1> YuNoTCKimlikNoGuncelleAsync(OgrenciService.YuNoTCKimlikNoGuncelleRequest YuNoTCKimlikNoGuncelleRequest)
        {
            OgrenciService.YuNoTCKimlikNoGuncelleRequest1 inValue = new OgrenciService.YuNoTCKimlikNoGuncelleRequest1();
            inValue.YuNoTCKimlikNoGuncelleRequest = YuNoTCKimlikNoGuncelleRequest;
            return ((OgrenciService.OgrenciPort)(this)).YuNoTCKimlikNoGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.OgrenciEkleGuncelleResponse1> OgrenciService.OgrenciPort.OgrenciEkleGuncelleAsync(OgrenciService.OgrenciEkleGuncelleRequest1 request)
        {
            return base.Channel.OgrenciEkleGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.OgrenciEkleGuncelleResponse1> OgrenciEkleGuncelleAsync(OgrenciService.OgrenciEkleGuncelleRequest OgrenciEkleGuncelleRequest)
        {
            OgrenciService.OgrenciEkleGuncelleRequest1 inValue = new OgrenciService.OgrenciEkleGuncelleRequest1();
            inValue.OgrenciEkleGuncelleRequest = OgrenciEkleGuncelleRequest;
            return ((OgrenciService.OgrenciPort)(this)).OgrenciEkleGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.OgrenciSilResponse1> OgrenciService.OgrenciPort.OgrenciSilAsync(OgrenciService.OgrenciSilRequest1 request)
        {
            return base.Channel.OgrenciSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.OgrenciSilResponse1> OgrenciSilAsync(OgrenciService.OgrenciSilRequest OgrenciSilRequest)
        {
            OgrenciService.OgrenciSilRequest1 inValue = new OgrenciService.OgrenciSilRequest1();
            inValue.OgrenciSilRequest = OgrenciSilRequest;
            return ((OgrenciService.OgrenciPort)(this)).OgrenciSilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.TeyitlesmeResponse1> OgrenciService.OgrenciPort.TeyitlesmeAsync(OgrenciService.TeyitlesmeRequest1 request)
        {
            return base.Channel.TeyitlesmeAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.TeyitlesmeResponse1> TeyitlesmeAsync(OgrenciService.TeyitlesmeRequest TeyitlesmeRequest)
        {
            OgrenciService.TeyitlesmeRequest1 inValue = new OgrenciService.TeyitlesmeRequest1();
            inValue.TeyitlesmeRequest = TeyitlesmeRequest;
            return ((OgrenciService.OgrenciPort)(this)).TeyitlesmeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.YokNoYuNoGuncelleResponse1> OgrenciService.OgrenciPort.YokNoYuNoGuncelleAsync(OgrenciService.YokNoYuNoGuncelleRequest1 request)
        {
            return base.Channel.YokNoYuNoGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.YokNoYuNoGuncelleResponse1> YokNoYuNoGuncelleAsync(OgrenciService.YokNoYuNoGuncelleRequest YokNoYuNoGuncelleRequest)
        {
            OgrenciService.YokNoYuNoGuncelleRequest1 inValue = new OgrenciService.YokNoYuNoGuncelleRequest1();
            inValue.YokNoYuNoGuncelleRequest = YokNoYuNoGuncelleRequest;
            return ((OgrenciService.OgrenciPort)(this)).YokNoYuNoGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OgrenciService.YokYabanciOgrenciEkleResponse1> OgrenciService.OgrenciPort.YokYabanciOgrenciEkleAsync(OgrenciService.YokYabanciOgrenciEkleRequest1 request)
        {
            return base.Channel.YokYabanciOgrenciEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OgrenciService.YokYabanciOgrenciEkleResponse1> YokYabanciOgrenciEkleAsync(OgrenciService.YokYabanciOgrenciEkleRequest YokYabanciOgrenciEkleRequest)
        {
            OgrenciService.YokYabanciOgrenciEkleRequest1 inValue = new OgrenciService.YokYabanciOgrenciEkleRequest1();
            inValue.YokYabanciOgrenciEkleRequest = YokYabanciOgrenciEkleRequest;
            return ((OgrenciService.OgrenciPort)(this)).YokYabanciOgrenciEkleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OgrenciPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OgrenciPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://servisler.yok.gov.tr/ws/ogrencibilgitoplamav4");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OgrenciPortClient.GetBindingForEndpoint(EndpointConfiguration.OgrenciPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OgrenciPortClient.GetEndpointAddress(EndpointConfiguration.OgrenciPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            OgrenciPortSoap11,
        }
    }
}
